1 setup online store
AnaLanda/jv-online-store pull request #1
Opened 2020-09-02 15:40 UTC by AnaLanda

2020-09-02 15:53 UTC, aleksandr-hrankin commented on src/main/java/dao/impl/ProductDaoImpl.java
> +        Storage.products.removeIf(x -> x.getId().equals(productId));
метод removeIf возвращает boolean)

2020-09-02 15:53 UTC, aleksandr-hrankin commented on src/main/java/dao/impl/ProductDaoImpl.java
> +        }
Можно обойтись без Optional, сразу возвращать product

2020-09-02 16:50 UTC, AnaLanda commented on src/main/java/dao/impl/ProductDaoImpl.java
> +        Storage.products.removeIf(x -> x.getId().equals(productId));
Спасибо, Саш! Недосмотрела)

2020-09-03 08:44 UTC, dmytro-hryhoruk commented on pom.xml
>  </project>
add empty line to the end of file

2020-09-03 08:44 UTC, dmytro-hryhoruk commented on src/main/java/com/internet/shop/db/Storage.java
> +        products.add(product);
let's first set id and then increment it so the first product Id will be zero

2020-09-03 08:44 UTC, dmytro-hryhoruk commented on src/main/java/com/internet/shop/model/Order.java
> +    Long userId;
access modifiers

2020-09-03 08:44 UTC, dmytro-hryhoruk commented on src/main/java/com/internet/shop/model/Order.java
> +    List<Product> products = new ArrayList<>();
let's move this list initialization to constructor

2020-09-03 08:44 UTC, dmytro-hryhoruk commented on src/main/java/com/internet/shop/model/Product.java
> +    double price;
access modifier

2020-09-03 08:44 UTC, dmytro-hryhoruk commented on src/main/java/com/internet/shop/model/ShoppingCart.java
> +    Long userId;
same

2020-09-03 08:44 UTC, dmytro-hryhoruk commented on src/main/java/com/internet/shop/model/User.java
> +    String password;
and here

2020-09-03 08:52 UTC, AnaLanda commented on src/main/java/com/internet/shop/model/User.java
> +    String password;
:woman_facepalming:

2020-09-03 12:45 UTC, dmytro-hryhoruk commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +                .orElse(null);
let's check this implementation. print all Storage list before updating this product and after

2020-09-03 14:38 UTC, KseniiaMakarova requested changes
also, in this PR let's fix the last line of your `gitignore`

2020-09-03 14:38 UTC, KseniiaMakarova commented on pom.xml
> +    </dependencies>
let's remove `<dependencies>` block for now - we don't use dependencies yet

2020-09-03 14:38 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +                .orElse(null);
this doesn't cause changes in our storage
the elements are changed only in this stream

let's create IntStream of indices, than filter out only those indices on which there are elements with the same id
then for each of the remaining indices, replace the element in storage with our `product`

also, return `product` in each case

2020-09-03 14:38 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/Order.java
> +    private Long userId;
getters and setters would be nice :)

2020-09-03 14:38 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/ShoppingCart.java
> +    private Long userId;
same here

2020-09-03 14:38 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/User.java
> +    private String password;
same here

2020-09-03 15:29 UTC, KseniiaMakarova requested changes
please fix last line in your `gitignore`

it is currently `target/*git`, should be `target/*`

2020-09-03 15:29 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +                .ifPresent(originalProduct -> products.set(originalProduct, product));
```suggestion
        IntStream.range(0, products.size())
                .filter(index
                        -> products.get(index).getId().equals(product.getId()))
                .forEach(index -> products.set(index, product));
```

2020-09-03 15:31 UTC, dmytro-hryhoruk commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +                .ifPresent(originalProduct -> products.set(originalProduct, product));
```suggestion
                .filter(i -> products.get(i).getId().equals(product.getId()))
                .forEach(i -> products.set(i, product));
```

2020-09-03 15:47 UTC, AnaLanda commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +                .ifPresent(originalProduct -> products.set(originalProduct, product));
Thanks))

2020-09-03 15:47 UTC, AnaLanda commented on src/main/java/com/internet/shop/dao/impl/ProductDaoImpl.java
> +                .ifPresent(originalProduct -> products.set(originalProduct, product));
Thanks))

2020-09-03 16:12 UTC, KseniiaMakarova approved these changes

2020-09-07 09:14 UTC, merged