replaced predefined USER_ID with data from Session
AnaLanda/jv-online-store pull request #7
Opened 2020-09-15 09:08 UTC by AnaLanda

2020-09-15 09:51 UTC, matviichuk92 approved these changes
good job!

2020-09-16 04:48 UTC, KseniiaMakarova requested changes

2020-09-16 04:48 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/order/GetAllUserOrdersController.java
> +        Long userId = (Long) session.getAttribute("user_id");
```suggestion
        Long userId = (Long) session.getAttribute(USER_ID);
```

2020-09-16 06:58 UTC, KseniiaMakarova approved these changes

2020-09-16 08:08 UTC, merged